### ISSUE TITLE
Attempting to Open the Docs on Ubuntu Tar Crashes Workbench

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#33870] opened 2022-05-11 10:34 UTC
**Describe the bug**
When opening the docs from the help on the menu bar or from any of the `?` buttons, workbench crashes to desktop. 

Note: This is only a crash on Ubuntu, the other OSs (windows and macOS tested) just have a blank docs navigator. 

**To Reproduce**
1. Install and launch the new packaged nightly (the one on babylon)
2. Navigate to Help -> Mantid Help
3. Observe crash

**Expected behavior**
The docs should appear populated. 

**Platform/Version (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 18.04
 - Mantid Version: 6.3.20220510.2145

**Additional context**
This may be related to an issue in the docs packaging process.

**Comment by martyngigg** [comment] 2022-05-12 08:02
I'm going to close this as a duplicate of #33881 as that the real cause.

**Closed by martyngigg** 2022-05-12 08:02 UTC
Labels: High Priority, Bug, Linux Only
