### ISSUE TITLE
Python generated code from SANS GUI V2 does not work

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#22097] opened 2018-03-15 10:08 UTC
I've just noticed that the Python code generated by the Output Notebook option on the new SANS GUI gives this error when you run the notebook: NameError: name 'SANSGuiDataProcessorAlgorithm' is not defined.

**Comment by TTitcombe** [comment] 2019-03-28 13:58
Duplicate of #21519

**Closed by TTitcombe** 2019-03-28 13:58 UTC
Labels: Component: GUI, Component: SANS
