### ISSUE TITLE
X scale is not reversible in the figure options

### ISSUE THREAD

**Issue by MohamedAlmaki** [mantidproject/mantid#36268] opened 2023-10-10 11:14 UTC
In tIn the fit window, changing the x-scale type from linear to log and then back again does not return the figure to its original state.

**To Reproduce**
1- Plot spectrum on some sample
2. Click on the 'Fit' button
3. Click on the settings icon
4. Change the x scale from linear to log
5. Check the plot to ensure it is displaying correctly
6. Change the x scale back from log to linear
7. You will notice that the plot does not return to its original state

**Expected behavior**

The plot should remain unchanged from its previous state
**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: IDAaS (CentOS) [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version: 7 (Core)
 - Mantid Version [e.g. 6.0.0]: 6.8.0

**Additional context**

**Comment by jhaigh0** [comment] 2023-10-17 13:26
I think this is a duplicate of #36098

**Closed** 2023-11-09 08:30 UTC
Labels: Bug, ISIS Team: Core
