### ISSUE TITLE
Fitting result changes depending on log level

### ISSUE THREAD

**Issue by MichaelWedel** [mantidproject/mantid#11357] opened 2014-11-07 14:37 UTC
This issue was originally [TRAC 10515](http://trac.mantidproject.org/mantid/ticket/10515)

While I was doing some experimental work on POLDI 2D-fitting, I discovered that the result depends on the log level. For log-level information or debug, the fit converges differently and gives a different result.

Since this was experimental work, I will just push the small changes I made to reproduce this problem.

**Comment by FedeMPouzols** [comment] 2015-08-06 15:21
@MichaelWedel : for when you're back, I think that this issue was solved as #12948. And by the way we 'fixed' one of your Poldi tests for that change (see PR #12961) so please close this issue if you think that the problem is gone now.

**Comment by MichaelWedel** [comment] 2015-09-17 11:40
As suggested by @FedeMPouzols, the issue has been solved in another context, so I'm closing this issue.

**Closed** 2016-02-15 14:04 UTC
Labels: Component: Framework
