### ISSUE TITLE
MaskDetectors behavior changed

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#19399] opened 2017-04-18 23:33 UTC
I tried to run the following script
```
tomask=range(10)
w=LoadEmptyInstrument(InstrumentName='HYSPEC')
MaskDetectors(w,SpectraList=tomask)
```
### Expected behavior
Mask some detectors (some of them are monitors), and not to fail

### Actual behavior
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-f0dd7094376c> in <module>()
----> 1 MaskDetectors(w,SpectraList=tomask)

/opt/mantidnightly/bin/mantid/simpleapi.pyc in algorithm_wrapper(Workspace,SpectraList=None,DetectorList=None,WorkspaceIndexList=None,MaskedWorkspace=None,ForceInstrumentMasking=None,StartWorkspaceIndex=None,EndWorkspaceIndex=None,ComponentList=None, Version=1)
    932         set_properties(algm, *args, **final_keywords)
    933         try:
--> 934             algm.execute()
    935         except RuntimeError as e:
    936             if e.args[0] == 'Some invalid Properties found':

IndexError: _Map_base::at
```
### Steps to reproduce the behavior
Run the above script in the release (works), and in nightly (fails)
### Platforms affected
At least RHEL7 and Ubuntu 16.10, my guess is all

This also affects DGSPlanner interface

**Comment by SimonHeybrock** [comment] 2017-04-19 07:23
This might be a duplicate of https://github.com/mantidproject/mantid/issues/19289.

**Closed** 2018-07-11 09:56 UTC
Labels: Component: Framework, Misc: Bug, Priority: High
