### ISSUE TITLE
6.2 Testing - Fitting bugs

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#32439] opened 2021-09-09 10:05 UTC
**Describe the bug**

When attempting to do a fit from a plot in Mantid I have ran into a few problems.
1. I cannot get the fit to include the first data point
2. I cannot drag the fit range lines
3. If I update the endX in the fit browser, the line on the plot does not update (even after a fit)
4. After the fit the parameter values do not update

**To Reproduce**

Load some data, then plot it (I just made a 10 data point ws)
Switch the view from line to points
Try to update the start/end x values
Try to include the first/last data point (you can't)
Do a fit
Look at the parameter values - they have not updated

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by StephenSmith25** [comment] 2021-09-09 10:48
Maybe needs some more info. As this works for me, but there are some usability issues.

**Comment by AnthonyLim23** [comment] 2021-09-09 12:15
I ran the script below and when I tried to do the fitting I ran into the above problems.

```
PlotAsymmetryByLogValue(OutputWorkspace='data', LogValue='sample_magn_field', DeadTimeCorrType='FromRunData', WorkspaceNames=r'\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077776.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077777.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077778.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077779.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077780.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077781.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077782.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077783.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077784.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077785.nxs,\\isis.cclrc.ac.uk\inst$\ndxhifi\instrument\data\cycle_14_3\HIFI00077786.nxs')

```

**Comment by StephenSmith25** [comment] 2021-09-09 13:15
The range issues I think are a usability thing, so maybe not as important. But for me the parameters aren't updating as well. Seems like we've got a issue here....

**Comment by DavidFair** [comment] 2021-09-10 15:19
I've removed high priority for this meta issue, as the params not updating has been resolved.
I'm not sure if the other issues are outstanding

**Comment by martyngigg** [comment] 2021-09-10 15:54
Fixed by #32457

**Closed by martyngigg** 2021-09-10 15:54 UTC
Labels: Bug, ISIS Team: Core

**Comment by AnthonyLim23** [comment] 2021-09-13 08:07
@StephenSmith25 does the PR also fix the problem of not being able to select the whole range? It also seems to be a problem in inherited fit browsers https://github.com/mantidproject/mantid/issues/32478

**Comment by StephenSmith25** [comment] 2021-09-13 08:39
So maybe I'm missing something, but I appear to be able to fit to all the data, e.g - or is this not what you mean - as I was able to do this before.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/56431339/133051706-a8918a8f-9cd3-4370-8c7e-d3e9d2f83716.png">

**Comment by AnthonyLim23** [comment] 2021-09-13 08:44
When I used points for the plot, I was unable to get the first or last. @Harrietbrown has seen the same problem in indirect

**Comment by StephenSmith25** [comment] 2021-09-13 08:53
Did you set startX and endX to the bin dimensions, rather than the coordinates of the points / bin centres?

**Comment by AnthonyLim23** [comment] 2021-09-13 08:55
I couldn't even drag the fitting line to it

**Comment by StephenSmith25** [comment] 2021-09-13 09:00
You can still set the startX and endX in the fit browser though. If you set the startX to the first bin and endX to the last bin I observe that it fits the whole range - so from what I can tell there's no bug here, but I maybe missing something. I agree there's possibly some issues with the fit range markers though.

**Comment by AnthonyLim23** [comment] 2021-09-13 09:05
I just tried that on the data from the script above. I changed the start x and it did the fit as expected. I changed the end x and it moved the start x to exclude the first point again

**Comment by StephenSmith25** [comment] 2021-09-13 09:24
Moving the endX doesn't move the startX for me 😕

**Comment by AnthonyLim23** [comment] 2021-09-13 09:25
it is inconsistent, it just worked for me. Something does not seem right, but its hard to pinpoint

**Comment by StephenSmith25** [comment] 2021-09-13 09:32
I think there's some usability bugs with the markers, which we should look at next release. But the startX and endX properties of the fit algorithm seem to work as intended, well as far as I can tell.
