### ISSUE TITLE
Plot buttons not disabled in ISIS reflectometry

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24979] opened 2019-03-04 14:06 UTC
### Expected behavior
Should not be able to plot when rows have not been processed

### Steps to reproduce the behavior
Interfaces -> Reflectometry -> ISIS Reflectometry
Load a table
The "Plot selected runs" and "plot selected group" buttons above the table are not disabled. Clicking them results in an error

**Comment by gemmaguest** [comment] 2019-03-04 14:45
Duplicate of #22034

**Closed by gemmaguest** 2019-03-04 14:45 UTC
Labels: Component: GUI, Component: Reflectometry
