### ISSUE TITLE
Fit function browser should be text searchable

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#25794] opened 2019-05-29 15:44 UTC
### Expected behavior
* It should be possible to search the fit function browser using a string of text.

### Actual behavior
* It is currently only possible to search this by using the drop down box filtering which is not good enough given the number of fit functions we have!

### Steps to reproduce the behavior
* Load `HRP39180` from the training set data
* Right click the workspace and plot select `Plot Spectrum...`
* Enter any valid spectra Number / Workspace index into the `Plot Spectrum` dialog box
* Click the fit button (Labelled as `fit` in the workbench, or this button in MantidPlot 
![image](https://user-images.githubusercontent.com/13132128/58570889-a9c7de80-8230-11e9-88b4-bc22dd5cb251.png)
* Right click the functions selection in the now visible fit function browser and select `Add Function`.
* Observe that there is no way to search the large number of fit functions in the Function selection dialog box.

### Platforms affected
All

**Comment by alicerussell1** [comment] 2020-03-05 14:50
This is a duplicate of #27587 and has been done

**Closed by alicerussell1** 2020-03-05 14:50 UTC
Labels: Code Quality, Fitting, MantidPlot, Training, Workbench
