### ISSUE TITLE
Error compiling Fit.cpp with GSL >=2.0

### ISSUE THREAD

**Issue by eXeC64** [mantidproject/mantid#15622] opened 2016-03-09 12:51 UTC
[Line 144 of Fit.cpp](https://github.com/mantidproject/mantid/blob/master/MantidPlot/src/Fit.cpp#L144) causes a compilation error with newer versions of GSL. It fails because `J` has been removed from `gsl_multifit_fdfsolver` as part of some refactoring in newer versions of GSL: [Changelog](http://git.savannah.gnu.org/cgit/gsl.git/tree/NEWS).

Unfortunately, I'm not familiar enough with this area of Mantid to suggest a fix. [Here](https://fossies.org/dox/gsl-2.1/structgsl__multifit__fdfsolver.html) is the current API documentation for that struct.

As far as  I know, no officially supported platforms are shipping GSL >=2.0, however I've run into this issue on Arch Linux, and have had to reinstall the older version of GSL.

**Comment by rosswhitfield** [comment] 2016-03-09 13:50
Duplicate of #15421

**Closed by rosswhitfield** 2016-03-09 13:50 UTC
