### ISSUE TITLE
Execution of a Python script cannot be terminated

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11575] opened 2014-12-09 15:28 UTC
This issue was originally [TRAC 10733](http://trac.mantidproject.org/mantid/ticket/10733)

Using the Python script window once started a script cannot be stopped until it either reaches the end of the script of fails part way through.

It would be very handy to be able to stop a script running since there is potential to be running scripts that take a reasonable time to fully execute.

**Comment by martyngigg** [comment] 2015-08-03 08:10
Duplicate of #13265

**Closed** 2015-08-03 08:13 UTC
Labels: Component: GUI, State: Review Required
