### ISSUE TITLE
Unscripted Testing Muon

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#16172] opened 2016-05-12 16:28 UTC
1. Read http://www.mantidproject.org/Unscripted_Manual_Testing
2. Comment against this ticket the OS environment you are testing against.
3. Don't spend more than a few hours on the testing as fatigue will kick in.
4. If you find errors in the possibly scant documentation, then correct them.
5. Close the this ticket once you are done.

If you find bugs:
- Search to see if an issue already exists
- create an issue if it is new
  - Urgent bugs or crashes should by against the current release, and assigned to a developer, then go and talk to the developer if possible.
  - Less urgent bugs should be against a subsequent release, and assigned if the correct developer is known.
### Specific Notes:

As a minimum test http://www.mantidproject.org/Unscripted_Manual_Testing_MuonAnalysis.
For more info see http://www.mantidproject.org/Muon

Mantid 3.8 onwards: there is a new unscripted testing guide for the Data Analysis tab to be found here:
http://docs.mantidproject.org/nightly/interfaces/Muon_Analysis_unscripted_testing_guide.html

**Comment by tom-perkins** [comment] 2016-05-16 12:28
Windows 7 (as used by majority of muon scientists at present)

Note there is currently a crash using the muon interfaces on Ubuntu (#15984) - currently investigating.

**Comment by tom-perkins** [comment] 2016-05-16 14:40
Tested by running through the Mantid muon manual and the training school workbook. Found bugs #16224 and #15984.

**Comment by tom-perkins** [comment] 2016-09-19 16:32
Testing on Windows 7 using the muon manual and 2014 training school workbook.

**Comment by tom-perkins** [comment] 2016-09-22 09:03
Re-testing on Windows 7 because ~~#16855~~ is merged and the interface has significantly changed.
Using the new unscripted testing guide.
Also will test the ALC interface, which I didn't test before.
- [ ] Muon Analysis
- [ ] ALC

**Comment by KarlPalmen** [comment] 2017-01-25 10:09
I'm testing in Windows 7.

**Comment by KarlPalmen** [comment] 2017-01-25 10:53
I'm testing the release of January 23.

**Comment by KarlPalmen** [comment] 2017-01-25 11:41
All the scripted tests went OK, except test 7, which could not be completed, because the `Label for Simultaneous Fit`  box was disabled.

**Comment by KarlPalmen** [comment] 2017-01-25 12:29
This was because I followed the instructions in the order given. If follow the next instruction (set period checkboxes) first, I can then set the label.

**Comment by KarlPalmen** [comment] 2017-01-25 12:32
When I change the function to Linear Background (in group 2 test 7), I get an unexpected exception `ParamFunction LinearBackground does not have parameter (f1.Phi)`.

**Comment by KarlPalmen** [comment] 2017-01-25 13:54
I have not been able to reproduce this unexpected exception in a simple manner. It may have occurred because of a change in instrument. 

I've found another exception that occurs when one changes instrument. This can be produced by selecting an instrument do some data analysis on it then return to the home tab, then change instrument, then observe that the data analysis tab is still enabled, even though no data has been loaded for newly selected instrument. Selecting the data analysis tab leads to an unexpected exception.

**Comment by KarlPalmen** [comment] 2017-01-25 14:27
Group 3 (Results tables) not tested owing to above-mentioned unexpected exception in group 2 test 7.

**Comment by KarlPalmen** [comment] 2017-01-26 10:37
I tried group 2 test 1 followed by group 2 test 7 and when I tried to fix `linear background` and exception came up complaining about a non-existing parameter. I'll raise this as an issue.

**Comment by KarlPalmen** [comment] 2017-01-26 14:50
I tested group 3 using the Mantid overnight build of 25 January having run all of group 2, except test 7 and found the result tables were correct, taking account of the absence of the MUSR results arising from test 7 not being done.

**Comment by KarlPalmen** [comment] 2017-01-26 14:50
Everything OK except issue #18566.

**Closed** 2017-01-26 14:50 UTC
Labels: Quality: Manual Tests
