### ISSUE TITLE
`LoadEventNexus` can't load some ISIS datasets in debug mode

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18489] opened 2017-01-20 15:09 UTC
Some event datasets at ISIS have `event_id = 0` (this could mean that the encoding signal was corrupted somehow or that there's a detector which wasn't assigned a spectrum to it) which causes Mantid to crash at [this](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/ProcessBankData.cpp#L59) line. This issue is to fix this for the next release. The reason why this is not urgent is that when loading the problematic files in release mode, those events are just skipped, so that the data we end up with is correct.

### Expected behavior

We should be able to load file:

```
ws = Load(Filename=r'\\isis\inst$\ndxinter\instrument\data\cycle_16_2\INTER00038415.nxs')
```
in debug mode.

### Actual behavior

Mantid crashes.

### Steps to reproduce the behavior

Run the line above.

### Platforms affected

Windows, debug mode.

**Comment by gemmaguest** [comment] 2017-03-15 16:49
Closed as a duplicate of #19103

**Closed by gemmaguest** 2017-03-15 16:49 UTC
Labels: Component: Framework
