### ISSUE TITLE
Load memory leak

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#35646] opened 2023-06-05 15:24 UTC
When loading data we have a memory leak. The below script should always start and end at about the same memory usage (widget above the messages box). However, on my IDAaS it goes up from 0.3 to 0.5. 

```
start = 18587
num = 66
for j in range(num):
    run = start+j
    Load("HIFI"+str(run), OutputWorkspace="HIFI"+str(run))
   
AnalysisDataService.clear()
CleanFileCache()
```

**Comment by AnthonyLim23** [comment] 2023-06-06 07:55
Done a bit more investigating. This also happens for OSIRIS (0.3 -> 0.4) (could just be rounding error)
```
inst = "OSIRIS"
start = 26173
num = 66
for j in range(num):
    run = start+j
    Load(inst+str(run), OutputWorkspace=inst+str(run))
   
AnalysisDataService.clear()
CleanFileCache()
```
 

The leak does not seem to happen every time.

**Comment by RichardWaiteSTFC** [comment] 2023-06-06 07:57
Thanks @AnthonyLim23 for the script - this seems to happen with WISH: clearing 6 runs from the ADS often leaves ~15-20GB in RAM (a run is 20GB in memory) - but again it is difficult to reproduce.

```
for ntries in range(20):
    start = 50087
    nruns = 6
    for irun in range(nruns):
        run = start+irun
        Load("WISH000"+str(run), OutputWorkspace="WISH000"+str(run))
    AnalysisDataService.clear()
    CleanFileCache()
```

**Comment by MialLewis** [comment] 2023-06-06 08:13
Just posting this here to remind us that its user reported, and to feed back upon resolution. https://github.com/ISISNeutronMuon/mantid-isis-support/issues/117

**Comment by warunawickramasingha** [comment] 2024-02-15 11:10
I analysed the above issue with [Valgrind's Memcheck](https://valgrind.org/docs/manual/quick-start.html#quick-start.intro) tool and did not see any memory leak originating from the Mantid code base other than for many (thousand's) traces originating from other 3rd party libraries such as QT and boost which I have suppressed using [InitializeEditor.zip](https://github.com/mantidproject/mantid/files/14295877/InitializeEditor.zip) and tried calling the above load methods to check the output. In order to trace the leak points, have to build the workbench using Debug or RelWithDebInfo modes.

```valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrindoutput.log --suppressions=InitializeEditor.supp ./workbench --single-process```

However, when the files were loaded from the disk, there was a memory leak causing a considerable growth in the dynamic memory due to a missing `free` operation which is now fixed in the PR linked to this.

**Comment by GuiMacielPereira** [comment] 2024-02-21 09:36
After investigating this issue further in https://github.com/mantidproject/mantid/pull/36854, it looks like Load() is operating as expected, and not leaking the big amounts of memory mentioned above. @jclarkeSTFC also tried to replicate this issue but also did not manage to get any large amount of memory leak. 

There was however a small memory leak due to a pointer for reading workspace metadata not being properly deleted. This has now been addressed by @warunawickramasingha in the linked PR https://github.com/mantidproject/mantid/pull/36854. Any other remaining small memory leaks are likely due to third party software leaks, and not coming from the Load() function.

With this in mind, I would say its safe to close this issue when https://github.com/mantidproject/mantid/pull/36854 gets merged.

**Closed** 2024-02-21 11:38 UTC
Labels: Bug, ISIS Team: Core, Reported By User
