### ISSUE TITLE
Opening Instrument View with particular file crashes Workbench

### ISSUE THREAD

**Issue by jclarkeSTFC** [mantidproject/mantid#36911] opened 2024-02-21 15:18 UTC
**Original reporter:** Mo

**Describe the bug**
Opening Instrument View on MARI29307 on an IDAaaS instance will make Workbench disappear. No sad mantid.

**Platform/Version (please complete the following information):**
 - OS: IDAaaS Rocky Linux 8.9
 - Mantid Version 6.8, 6.9

**Additional context**
Found during 6.9 beta testing, but the problem is also in 6.8.

**Comment by jclarkeSTFC** [comment] 2024-06-18 10:50
I can't reproduce this anymore, even in 6.8

**Comment by thomashampson** [comment] 2024-06-18 11:00
This appears to be a duplicate of https://github.com/mantidproject/mantid/issues/36220 and IDAaaS have implemented a workaround for older versions of workbench.

**Closed by thomashampson** 2024-06-18 11:00 UTC
Labels: Bug, ISIS Team: Core, IDAaaS Only
