### ISSUE TITLE
Keyboard control of SpectrumViewer

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#15237] opened 2016-02-09 19:18 UTC
Keyboard control does not appear to work anymore. To reproduce try any of the following:
* Change `X Min`, `X Max`, or `Step(-if Log)` and get it to update the view
* Click on the main image then move the cursor to change where it is pointing. The horizontal and vertical graphs should update.
* When the view comes up, the vertical scrollbar is present, even when the data is resampled to fit the visible vertical axis.

This was observed on rhel7, f23, and ubuntu 15.10.

**Comment by AndreiSavici** [comment] 2016-02-09 22:48
Just some quick comments:
* once you click on the main image, move cursor using arrow keys
* the cursor moves, but the plots on the x and y axis do not  update
* I found the same behaviour in the previous release
* in MantidPlot 3.4.1, I cannot move the cursor  at all in the vertical direction, but it works as expected (including spectrum update) when I move left and right

**Comment by martyngigg** [comment] 2016-02-10 10:58
Confirmed both bullets on Ubuntu 14.04 too.

**Comment by mantid-roman** [comment] 2016-02-10 11:02
If you click the image then press Enter the plots will update using the keyboard. Press Enter again (or Esc) updating stops. Maybe it's a good thing.

**Comment by martyngigg** [comment] 2016-02-10 11:08
@mantid-roman That works for me too. It feels like something more visual like a checkbox for auto-updating would provide a better experience.

Does changing the X range do anything for you?

**Comment by mantid-roman** [comment] 2016-02-10 11:12
Agree.

Changing x range doesn't change the image, only after changing intensity. This should be fixed.

**Comment by peterfpeterson** [comment] 2016-02-10 15:08
The (apparently long broken) functionality is that changing the binning and pressing enter updated the image and related plots, moving the cursor (using keyboard) updated the plots and the tables.

**Comment by peterfpeterson** [comment] 2016-02-10 15:17
@mantid-roman You need to branch from `release-3.6.0` if you don't want to make it hard to merge.

**Comment by mantid-roman** [comment] 2016-02-10 15:19
I forgot

**Comment by peterfpeterson** [comment] 2016-02-10 15:29
That branch can be turned into a PR for merging into `master`.

**Comment by peterfpeterson** [comment] 2016-02-10 17:12
Your commit fixed the Xmin/Xmax issue. Updating spectra is still broken.

**Comment by peterfpeterson** [comment] 2016-02-10 22:05
For the arrow key issue I think 5ac1813624689ea082064b884bad6e1ae6e103dd matters most.

**Comment by mantid-roman** [comment] 2016-02-11 09:25
Now we have 3 branches :)

**Comment by peterfpeterson** [comment] 2016-02-11 14:04
The tip of the branch is really close.

**Comment by peterfpeterson** [comment] 2016-02-11 15:13
Only two branches. @mantid-roman made both.

**Comment by mantid-roman** [comment] 2016-02-11 15:45
Are we ready for PR?

**Comment by peterfpeterson** [comment] 2016-02-11 15:57
:+1:

**Closed** 2016-02-11 21:25 UTC
Labels: Priority: High
