### ISSUE TITLE
Mantid workbench crashed in IDAaaS when viewing instrument

### ISSUE THREAD

**Issue by warunawickramasingha** [mantidproject/mantid#37316] opened 2024-05-10 09:40 UTC
**Describe the bug**
Mantid workbench crashed in `IDAaaS` when viewing instrument when following below steps 

**To Reproduce**
1. Load MAR11060.raw
2. Show instrument
3. Display setting->tick `Use OpenGL`
4. Select `Full 3D` from the axis selection drop down from top left corner.
5. mantid crashed

**Note**: Same steps did not make a crash in Widows.

**Expected behavior**
No crashes!

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS:  Rocky Linux 8.9 (Green Obsidian)
 - OS Version:
 - Mantid Version 6.9.1

**Additional context**

**Comment by robertapplin** [comment] 2024-05-10 13:47
Thanks for reporting this! I will close it because its a duplicate of #36220

**Closed by robertapplin** 2024-05-10 13:47 UTC
Labels: Bug
