### ISSUE TITLE
Print button Workbench Plotting

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27703] opened 2020-01-13 16:57 UTC
**Original reporter:** [Adrian Hillier]

### Expected behavior
Print button on a plot should bring up a dialog to allow printing
### Actual behavior
Button seems to do nothing on Windows
### Steps to reproduce the behavior
Plot a simple plot in Workbench
### Platforms affected
Mantid Workbench all versions including the Nightly
Seems to be a windows and Mac issue! Works fine on Linux

**Comment by PhilColebrooke** [comment] 2020-01-21 13:36
![image](https://user-images.githubusercontent.com/52415735/72809137-f4c8b300-3c52-11ea-8d64-b4d62106758c.png)
This appears to no longer be an issue on Windows ¯\\\_(ツ)_/¯

**Comment by DanielMurphy22** [comment] 2020-01-28 13:05
The print button works on Windows builds but not on the Py3 Nightly Release. Could be a packaging issue.

**Comment by martyngigg** [comment] 2020-01-29 08:58
Starting workbench from a package build in a command line reports:

```QPrintDialog: Cannot be used on non-native printers``

but not for a developer build. I wonder if we are missing a plugin from the package.

**Comment by martyngigg** [comment] 2020-01-29 09:03
It does indeed look like we are not shipping the `printsupport` plugins with the Windows package. @DanielMurphy22 Could you confirm whether the print button works on macOS from a package?

**Comment by DanielMurphy22** [comment] 2020-01-29 09:13
Just checked, the print button does not work on MacOS packages.

**Comment by martyngigg** [comment] 2020-01-29 09:16
@DanielMurphy22 Thanks. I've created a pull request to fix Windows packaging. We can open a separate one for macOS.

**Comment by martyngigg** [comment] 2020-01-29 09:19
It looks like the macOS packaging suffers similar issues with plugin.

**Comment by martyngigg** [comment] 2020-01-29 09:54
Confirmed that this is **not** a problem on Linux packages as we don't package Qt ourselves.

**Comment by NickDraper** [comment] 2020-02-21 16:02
now have merged PR's for both windows and mac

**Closed by NickDraper** 2020-02-21 16:02 UTC
Labels: Added during Sprint, ISIS Team: CoreTeam, Windows Only, Workbench, macOS Only
