### ISSUE TITLE
GUI code in IPython crashes workbench

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#23752] opened 2018-10-10 11:28 UTC
@AndreiSavici created a small script that crashes the workbench when executing it in the ipython window.
```python
from qtpy import QtWidgets

class TestWidget(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super(TestWidget,self).__init__()
        self.edit_box=QtWidgets.QLineEdit(self)
        self.setLayout(QtWidgets.QVBoxLayout())
        self.layout().addWidget(self.edit_box)
        #self.edit_box.setText('33')

mainForm=TestWidget()
mainForm.show()
```
To get a segmentation fault, uncomment the `setText` line

**Comment by NickDraper** [comment] 2019-09-03 09:28
Duplicate of #23101

**Closed** 2019-09-03 09:28 UTC
Labels: Bug, Workbench
