### ISSUE TITLE
LiveData not working at ORNL

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#16309] opened 2016-05-19 15:02 UTC
I tried to load live data from HYSPEC or SEQUOIA, with a preprocessing step Algorithm - SumSpectra (no parameters), and a post processing step Rebin, with parameters "0,10,30000", both with and without quotes.  
### Expected behavior
Works in 3.5
### Actual behavior
On 3.6 (and nightly) I get `Property "PARAMS" is not set to a valid value: "Enter values for this property".`

If I use a post processing script instead  that contains just `output=Rebin(input,Params="0,10,30000")`, it seems to work.
### Platforms affected
I've tested on RHEL7 (analysis.sns.gov) and on my Ubuntu workstation

**Comment by mantid-roman** [comment] 2016-05-19 15:21
@AndreiSavici #16306 should fix it.

**Comment by NickDraper** [comment] 2016-05-20 08:13
duplicate of #16203

**Closed by NickDraper** 2016-05-20 08:13 UTC
Labels: Component: Live Data, Priority: High, State: Review Required
