### ISSUE TITLE
Export fit table/results in muon to be compatable with WIMDA

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#32991] opened 2021-11-16 14:03 UTC
We need to check the WIMDA documents for the formatting of their results tables to see how we could have ours be compatable.

**Comment by sf1919** [comment] 2021-11-16 15:11
I think this is a duplicate of #32730 perhaps?

**Comment by AnthonyLim23** [comment] 2021-11-17 16:09
yes I think it is

**Closed by AnthonyLim23** 2021-11-17 16:09 UTC
Labels: Muon, ISIS Team: Spectroscopy
