### ISSUE TITLE
LoadDialog doesn't resize correctly

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#25790] opened 2019-05-29 15:29 UTC
the `Load` algorithm dialog does not resize to show the full array of properties once the file (henc exact loader) has been selected. User has to resize dialog window themselves, which is annoying.

**Comment by DanielMurphy22** [comment] 2020-04-28 16:31
WB and Plot 5.0 seem to have the same behaviour now, which is they resize, maybe not to fully show the whole array or properties, but most.
 Anyhow, I think this is worth discussion so re-labelling.

**Comment by martyngigg** [comment] 2020-12-17 09:03
This appears to still be an issue. This is the Load dialog after selecting an `_event.nxs` file:
![Screenshot 2020-12-17 at 09 01 59](https://user-images.githubusercontent.com/733773/102466247-ae3c2e00-4046-11eb-805c-c3b60197aa1b.png)

It would be good to try and give it some type of minimum size.

**Comment by thomashampson** [comment] 2021-02-09 18:02
Cannot reproduce the issue in Windows.

**Comment by joseph-torsney** [comment] 2021-04-20 10:34
Closing as we are not able to reproduce this

**Closed by joseph-torsney** 2021-04-20 10:34 UTC
Labels: Bug, ISIS Team: Core, Induction
