### ISSUE TITLE
MantidPlot crashes when fitting in Indirect Data analysis interface

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26154] opened 2019-07-03 13:56 UTC
When using ConvFit for fitting a ElasticDiffRotDiscreteCircle function MantidPlot crashes without error messages.

### Expected behavior
The Interface performs the fit, if this is not possible it should return an error.

### Actual behavior
A segmentatuon fault occurs and MantidPlot crashes.

### Steps to reproduce the behavior
- Interaces->Indirect->Data analysis->ConvFit
- in single input load Sample and resolution file (eg. irs26176_graphite002_red.nxs and irs26173_graphite002_res.nxs)
- In Fit function->Fit Type select ElasticDiffRotDiscreteCircle

### Platforms affected
Tried on Ubuntu 18

**Comment by robertapplin** [comment] 2019-07-04 13:38
The code causing the problem is being replaced by Roman who is working on Simultaneous fitting, so this is low priority. Once simultaneous fitting has been finished, this issue should be checked again.

**Comment by robertapplin** [comment] 2019-07-05 10:56
@mantid-roman do you think this should be fixed for this release? If so, might it be possible for you to have a look?

**Comment by mantid-roman** [comment] 2019-07-05 12:08
I'll have a look

**Closed** 2019-07-09 10:59 UTC
Labels: Component: GUI, Component: Indirect Inelastic, Priority: Low
