### ISSUE TITLE
Crash on click column option in MantidPlot table

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#16082] opened 2016-05-06 10:33 UTC
### Expected Behaviour

No crash

### Actual behavior

Crash

### Steps to reproduce the behavior

Run the following script:

```python
w = CreateEmptyTableWorkspace()
w.addColumn('str', 'Code')
w.addColumn('str', 'Value')
w.addRow(['',''])
w.addRow(['',''])
```

Double click on the table to view it, right click on the *Code* column and click column options and  :boom: 

### Platforms affected

All

**Comment by martyngigg** [comment] 2016-05-06 10:34
@tom-perkins This mimics what is done with James Lord's `CreateEmptyTableForQuantum` algorithm that a user just showed me. `v3.6.0` does not crash so we've introduced the bug this release. I suspect something around the Qt3 changes so @mantid-roman may be able to help.

**Comment by AndreiSavici** [comment] 2016-05-06 13:01
This is duplicate of #15915

**Comment by martyngigg** [comment] 2016-05-06 13:04
Confirmed as duplicate of #15915. I'll add to the PR  as fixing that issue too.

**Closed** 2016-05-06 17:20 UTC
Labels: Component: GUI, Priority: High
