### ISSUE TITLE
SliceViewer crash when opened using MAR training data

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#26116] opened 2019-07-02 13:38 UTC
###Expected behavior
No crash. 

### Actual behavior
Crashes the Workbench.

### Steps to reproduce the behavior
1. Load `MAR11060.raw` from the TrainingCourseData.
2. Right click the loaded workspace and select `Show SliceViewer`. There is a crash.

### Platforms affected
Found on Windows

**Comment by quantumsteve** [comment] 2019-07-08 16:04
Can't reproduce the issue with `master` on Ubuntu 18.04

**Comment by NickDraper** [comment] 2019-07-10 13:11
Duplicate of #26235

**Closed by NickDraper** 2019-07-10 13:11 UTC
Labels: Component: Workbench, Misc: Bug
