### ISSUE TITLE
Multiple fitting muon label

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#22673] opened 2018-06-26 11:37 UTC
The label for the simultaneous fitting is not updating correctly when the run changes (in the muon GUI).

If the workspace already exists it should cancel the fit and not append the name

**Comment by NickDraper** [comment] 2018-07-10 08:51
@AnthonyLim23 Is this a duplicate of #22824 ?

**Comment by AnthonyLim23** [comment] 2018-07-10 09:28
ah no. This is different. So here if the user has created a custom name (say bob) then does a second fit it should ask if the user wants to overwrite. If the user clicks no the fit should be cancelled. 

Issue #22824 is the name becoming rubbish under certain circumstances.

**Comment by NickDraper** [comment] 2018-07-13 10:54
@AnthonyLim23 What is the state of this issue?
Is there a PR, Is it vital for this release?

**Comment by AnthonyLim23** [comment] 2018-07-13 11:09
this can be next release. Its more of a new feature than a bug fix

**Closed** 2019-07-19 12:05 UTC
Labels: Component: Muon, Misc: Bug
