### ISSUE TITLE
Expose WorkspaceGroup constructor  in Python

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#18161] opened 2016-12-01 16:39 UTC
Currently there is no way to create a `WorkspaceGroup` in Python without using `GroupWorkspaces` which places my workspace into the ADS. Once the workspace is on the ADS, it is there essentially forever. This is not desirable. We need a way to create a `WorkspaceGroup` without going through the ADS.

**Comment by TWJubb** [comment] 2018-09-06 10:34
Closed as a more recent duplicate of this issue exists (#23448)

**Closed by TWJubb** 2018-09-06 10:34 UTC
Labels: Component: Framework
