### ISSUE TITLE
Change ISIS user file to python or other format

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12141] opened 2015-03-10 09:31 UTC
The 'user file' is a term used by the ISIS SANS group to an input 'parameter file' users can edit and which drives data reduction.

This change is partially technically driven to switch to format easier to maintain.

New format to consider includes JSON, YAML and Python dictonary.

Need to maintain backward compatability.

Contact: Steve King

---

Keywords: SSC, 2015, RAL, sansUI

**Comment by AntonPiccardoSelg** [comment] 2017-05-18 10:37
This is an issue which is brought to my attention quite often by the SANS scientists.
Recently Reflectometry scientists have expressed the need for user files. 

This would be a good opportunity to unify our approach.

**Comment by gemmaguest** [comment] 2019-10-02 14:01
Duplicate of #18826

**Closed by gemmaguest** 2019-10-02 14:01 UTC
Labels: High Priority, ISIS Team: LSS, MantidPlot, SANS
