### ISSUE TITLE
Muon Thread model

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#23767] opened 2018-10-11 08:42 UTC
In PR #23763 the thread model was reverted to prevent crashes of muon interfaces (frequency domain analysis and elemental analysis) on master. Below are the steps to cause one of the crashes (on linux): 

Open muon analysis and load some data
Then open the frequency domain analysis GUI
Change to maxent
Tick the use phases box in the table
Click the calculate button - it should give a warning box and not crash

**Comment by TWJubb** [comment] 2018-10-11 09:59
I will check this out straight away; I have a Linux build building. I may ask for the error report from the log if I can't reproduce it... I assume there were some python-esque errors showing?

**Comment by TWJubb** [comment] 2018-10-11 13:33
This can be fixed in a single line;

The `ThreadModel` class should inherit from `QtGui.QWidget` rather than `QtCore.QObject`.

**Comment by TWJubb** [comment] 2018-10-11 13:34
Just to be certain, the error box contains the text

```
Cannot currently generate phase table from this data using CalMuonDetectorPhases
```

is that correct?

**Comment by AnthonyLim23** [comment] 2018-10-11 15:19
yep, that is the correct error message

**Closed** 2019-01-08 10:42 UTC
Labels: Component: Muon
