### ISSUE TITLE
Indirect Corrections has no checks on inputs having different kinds of data

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#33376] opened 2022-01-25 13:25 UTC
Indirect Correction interface can be made to crash if the sample and container are different kinds of data.

Reported by Sanghamitra Mukhopadhyay

**To Reproduce**
1. open Indirect->Corrections
2. Load assocaited `_sqw` **will be added when obtained**
3. Load associated `_red` **will be added when obtained**

**Comment by SpencerHowells** [comment] 2022-01-25 14:07
@Harrietbrown what corrections tab?

**Comment by AnthonyLim23** [comment] 2022-01-25 14:28
I got this to crash on nightly using: 

osiris126202_multi_graphite002_red.nxs as the sample
osiris126202_multi_graphite002_sqw.nxs as the container 

However, the next attempt threw an error.

**Comment by sf1919** [comment] 2022-01-25 14:28
I'm unable to recreate a crash. If I open the Indirect->Corrections GUI and on the first tab (Container Subtraction) I added a _sqw sample and a _red container file. Nothing happens until I press run at which point the user receives a pop up error explaining the Sample and Container do not have a matching number of histograms

![Screenshot (119)](https://user-images.githubusercontent.com/55837273/150995506-ee5cb1d9-cd77-46f7-9b13-649a968ab0a4.png)

**Comment by AnthonyLim23** [comment] 2022-01-25 14:31
I think its just an error where something hangs for a little to long at random and this causes a crash

**Comment by sf1919** [comment] 2022-01-25 14:32
I've also now tried it the same way around as @AnthonyLim23 and get the error message but no crash. I'm doing this on a new branch created from release-next

**Comment by AnthonyLim23** [comment] 2022-01-25 14:33
I think its caused at random and we are not going to be able to reliably reproduce it

**Comment by Harrietbrown** [comment] 2022-01-25 14:37
If we are unable to replicate it then this should be a low priority issue

**Comment by SpencerHowells** [comment] 2022-01-25 14:54
@AnthonyLim23 @sf1919 @Harrietbrown In the tabs there is a filter for _red pseudoextension. It is there for a reason!!!! Anyone changing it to _sqw can expect things to go wrong!

**Comment by AnthonyLim23** [comment] 2022-01-27 12:05
I will try again this afternoon to reproduce this, if I cannot then I will close the issue.

**Comment by AnthonyLim23** [comment] 2022-01-27 13:41
I couldnt reproduce this, so I am closing it

**Closed by AnthonyLim23** 2022-01-27 13:41 UTC
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy
