### ISSUE TITLE
Remove deprecated SANS GUI

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#29149] opened 2020-08-07 11:56 UTC
Old SANS GUI in `\mantid\qt\scientific_interfaces\ISISSANS` is marked as deprecated in the `SansRunWindow.h`, removal would help to avoid confusion with the new interface files in `\mantid\scripts\Interface\ui\sans_isis`

**Comment by gemmaguest** [comment] 2020-08-07 13:32
Duplicate of #25916

**Closed by gemmaguest** 2020-08-07 13:32 UTC
Labels: ISIS Team: LSS, Maintenance, SANS
