### ISSUE TITLE
Tie expressions cannot have whitespace

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27924] opened 2020-02-12 16:00 UTC
### Expected behavior 
Can input `2 - f0.Height` as tie expression

### Actual behavior
needs to be `2-f0.Height` but this wasn't always the case
### Steps to reproduce the behavior
https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/fitting_data/01_fitting_models_to_data.html#tying-and-constraining-fit-parameters
### Platforms affected
This is a regression since 4.2, seen in a Py3 Nightly

**Comment by alicerussell1** [comment] 2020-02-12 16:52
This doesn't seem to be an issue in master and @DanielMurphy22 can't reproduce it so closing the issue

**Closed by alicerussell1** 2020-02-12 16:52 UTC
Labels: Fitting, ISIS Team: CoreTeam
