### ISSUE TITLE
Sliceviewer zoom to rectangle error

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#33733] opened 2022-04-04 13:35 UTC
**Describe the bug**
Sliceviewer reports an error when trying to use the "zoom to rectangle" tool. This occurs in a conda environment with matplotlib 3.5.

```
Traceback (most recent call last):
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\backend_bases.py", line 3191, in drag_zoom
    self.draw_rubberband(event, x1, y1, x2, y2)
  File "c:\workdir\mantid_conda_dev\mantid\qt\python\mantidqt\mantidqt\plotting\mantid_navigation_toolbar.py", line 141, in draw_rubberband
    self.canvas.drawRectangle(rect)
  File "C:\workdir\mantid_conda_dev\mantid\qt\applications\workbench\workbench\plotting\mantidfigurecanvas.py", line 47, in drawRectangle
    self._drawRect = [pt / self._dpi_ratio for pt in rect]
  File "C:\workdir\mantid_conda_dev\mantid\qt\applications\workbench\workbench\plotting\mantidfigurecanvas.py", line 47, in <listcomp>
    self._drawRect = [pt / self._dpi_ratio for pt in rect]
AttributeError: 'SliceViewerCanvas' object has no attribute '_dpi_ratio'
```

**To Reproduce**
1. Open a workspace, e.g. MAR11060 from the training course data
2. Open the sliceviewer
3. Make sure the "zoom to rectangle" tool is selected
4. Click on the plot (you might need to click and drag)

**Expected behavior**
No error.

**Platform/Version (please complete the following information):**
 - OS: I think this is only since moving to matplotlib 3.5 in a Conda environment
 -

**Comment by sf1919** [comment] 2022-04-08 07:17
duplicate of #33687

**Closed** 2022-04-25 14:44 UTC
Labels: Bug, ISIS Team: Core
