### ISSUE TITLE
Deprecated call in simpleapi.py

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#13911] opened 2015-10-09 02:50 UTC
In the new release we get this warning that goes into the error channel. That messes up the autoreduction process at SNS
```/opt/Mantid/bin/mantid/simpleapi.py:762: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  raise RuntimeError(e.message)```

**Comment by martyngigg** [comment] 2015-10-09 07:19
Does it only come out on the console error channel? I wonder why we have just started seeing this now?

**Comment by martyngigg** [comment] 2015-11-19 10:22
Duplicate of ~~#14333~~

**Closed** 2015-11-19 10:22 UTC
Labels: Component: Python, Misc: Bugfix, Patch Candidate, Priority: High
