### ISSUE TITLE
Update EngDiff UI dev testing docs

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33245] opened 2022-01-10 09:27 UTC
**Describe the outcome that is desired.**
Points arising from manual testing for 6.3 release - #33191 

- update image for the calibration tab
- update image for focus tab
- under test 5 need to add instructions on how to load multiple runs

**Comment by DannyHindson** [comment] 2022-09-13 08:59
I think this is a duplicate of #33878 so I'm closing

**Closed by DannyHindson** 2022-09-13 08:59 UTC
Labels: Documentation, Maintenance, ISIS Team: Diffraction
