### ISSUE TITLE
Plot an individual fit function

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27926] opened 2020-02-12 16:37 UTC
### Expected behavior This works in Mantidplot:
Right-clicking on a fit function and selecting Plot should produce a plot of this individual function
### Actual behavior
Nothing happens!
### Platforms affected
Workbench all

**Comment by martyngigg** [comment] 2020-10-27 15:14
Duplicate of #29622

**Closed by martyngigg** 2020-10-27 15:14 UTC
Labels: Bug, ISIS Team: Core, Workbench
