### ISSUE TITLE
DAQ and Detector deadtime

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12088] opened 2015-03-04 14:41 UTC
sans_feature
This issue was originally [TRAC 11249](http://trac.mantidproject.org/mantid/ticket/11249)

(DAQ: delay from readout and ADC conversion. Detector: delay from intrinsic ion pair/photon production)

Don’t know the physics of this. Including can delays from DAQ and detector can distinguished. 

Priority 4 - fairly low

Contacts:
- William Heller
- Richard Heenan
- Andrew Jackson (ESS)
  ---
  
  Keywords: SSC, 2015, sansCorr

**Comment by AntonPiccardoSelg** [comment] 2017-06-19 08:48
At the user meeting 2017 it was made clear that it is in parts still not clear how to handle this. The priority was considered appropriate

**Comment by gemmaguest** [comment] 2019-09-04 14:05
Closing as a duplicate of #9937

**Closed by gemmaguest** 2019-09-04 14:05 UTC
Labels: High Priority, ISIS Team: LSS, SANS
