### ISSUE TITLE
HistogramData rollout: QwtWorkspaceBinData.cpp to DPDFInputDataControl.cpp

### ISSUE THREAD

**Issue by PranavBahuguna** [mantidproject/mantid#18793] opened 2017-02-10 09:15 UTC
This issue is part of the HistogramData rollout, see #17641.
Algorithms covered in this issue are:

- MantidQt/API/src/QwtWorkspaceBinData.cpp
- MantidQt/API/src/QwtWorkspaceSpectrumData.cpp
- MantidQt/CustomDialogs/src/FitDialog.cpp
- MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/MultiDatasetFit/MDFDatasetPlotData.h
- MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/Muon/ALCBaselineModellingView.h
- MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/Muon/ALCDataLoadingView.h
- MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/Muon/ALCPeakFittingView.h
- MantidQt/CustomInterfaces/src/DynamicPDF/DPDFDisplayControl.cpp
- MantidQt/CustomInterfaces/src/DynamicPDF/DPDFFourierTransform.cpp
- MantidQt/CustomInterfaces/src/DynamicPDF/DPDFInputDataControl.cpp

**Comment by PranavBahuguna** [comment] 2017-03-31 09:20
Issue has been reopened as plotting has been reported to be broken after merge.

**Comment by LamarMoore** [comment] 2017-03-31 12:42
@SimonHeybrock @mdoucet the issue has been re-opened to fix the plotting issue.  When I checked his code out previously to find the source of a failing unit tests I ran all of the unit tests locally and they all passed, so this plot failing is bizarre. I am not going to be here to keep an eye on this over the next two weeks. Do you think you would be able to monitor the outcome of the fix?

**Comment by SimonHeybrock** [comment] 2017-03-31 12:45
@LamarMoore I don't think there are units tests for this, so you would not see the issue there. I will also be away for most of the next two weeks, so unfortunately I cannot have an eye on this.

**Comment by PranavBahuguna** [comment] 2017-03-31 12:53
@SimonHeybrock Do you know what plotting is being broken here?

**Comment by SimonHeybrock** [comment] 2017-03-31 12:56
See #general three days ago. The issue is the normalization flag that can be set.

**Comment by martyngigg** [comment] 2019-10-22 13:50
Closing as not worth consolidated effort in maintenance. Reveiwers can pick up and improve remaining code over time.

**Closed by martyngigg** 2019-10-22 13:50 UTC
Labels: Framework, Maintenance
