### ISSUE TITLE
Sliceviewer (symm)log scale issues

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29641] opened 2020-09-29 14:19 UTC
**Original reporter:** Jos Cooper on [the forum](https://forum.mantidproject.org/t/sliceviewer-intensity-scaling-in-workbench/693)

I think the solution here is likely to change to using the MPL scale Log rather than SymmLog. The experience for the user should be very similar to colorfill plots with a Log Scale. If this is implemented, it is worth checking that this does not distort the many other expected behaviours in sliceviewer.

### Expected behavior
The logarithmic colorbar makes physical sense and the minor ticks exist at magnitudes smaller than 1e-8
### Actual behavior
Possible to have 0 or -ve number as a limit (unphysical). There are no minor ticks between 1e-8 and 0. Also, currently the lower limit is ignored ( I think at these particularly small magnitudes: see [the forum](https://forum.mantidproject.org/t/sliceviewer-intensity-scaling-in-workbench/693).
### Steps to reproduce the behavior
Load OFFSPEC00060395 from the ISIS data archive
Show sliceviewer.
Change scale to SymmLog10, and notice how the _default_ lower limit is 0!
### Platforms affected
Workbench All

**Comment by martyngigg** [comment] 2020-10-27 15:25
Duplicate of #27959

**Closed by martyngigg** 2020-10-27 15:25 UTC
Labels: ISIS Team: Core, Workbench
