### ISSUE TITLE
Investigate refactoring Meier Test

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#34695] opened 2022-11-09 16:19 UTC
**Describe the outcome that is desired.**
Refactor the MeierTest to improve it and enable the test to be run on Linux machines.

**Does the outcome relate directly to a problem? Please describe.**
During recent work to  introduce new cloud linux nodes we found that we were having trouble with the MeierTest (see https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/test/python/plugins/functions/MeierTest.py). The test still works on  Windows and OSX machines and so a temporary fix to skip the final test on Linux machines has been implemented (see #34615) .

The test is not well written and needs to be refactored. This may help with the issue of running it on Linux and mean we can reverse the temporary fix.

**Describe any solutions you are considering**
@AnthonyLim23 has suggested the following solution

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
from scipy import optimize
from math import isnan

x = np.linspace(0,10)
jj = 2.5
y = 0.2*np.sin(x*2.3 + jj)

noise = np.random.rand(len(y))
y = y*(1+0.1*(noise-0.5))

e = 0.1*y

ws = CreateWorkspace(x,y,e)

plt.plot(x,y,'k-', label='data')
    


class getFunc(object):
    def __init__(self, j):
        self.j = j      
        
    def __call__(self, x, A, freq):
        tmp = A*np.sin(x*freq + self.j)
        return tmp

def fit(x,y,e, func, p0):

    popt, pcov = optimize.curve_fit(func, x,y,p0,sigma=e, absolute_sigma = True)
    chisq = np.sum(((y-func(x, *popt))/e)**2)
    chisq = chisq/(len(x) - len(popt))
    out = CreateWorkspace(x, func(x, *popt))
    return out, chisq, popt
    
    
def J_fit(ws, func, p0, jmin, jmax):
    J_list = np.linspace(jmin, jmax, jmax*2+1)
    outws = []
    chisq = []
    popt = []
    
    for j in J_list:
        func.j = j
        out, chi, pop = fit(ws.readX(0), ws.readY(0), ws.readE(0), func, p0)
        if not isnan(chi):
            outws.append(out)
            chisq.append(chi)
            popt.append(pop)

    minima = np.min(chisq)
    index = np.where(chisq == minima)
    index = index[0][0]
    fun.j = J_list[index]
    return fun(ws.readX(0), *popt[index]), chisq[index], popt[index]


fun = getFunc(1)
out, chi, popt = J_fit(ws, fun, [0.1, 2.], 0, 5)
print(chi, popt, fun.j)
plt.plot(x, out, 'b--', label="fit")


plt.legend()
plt.show()
```

It may also be worth considering refactoring both the Meier fitting function and its tests in C++.

**Comment by AnthonyLim23** [comment] 2022-11-09 16:57
Due to the summations involved within the function, moving to C++ should result in a nice speed increase. 

The main issue is that the fit engine struggles due to the spin only having half integer values. So when the minimizer makes a step, say from 1. to 1.1 (and keeps all of the other parameters the same) it will get the exact same result. This can cause at least 2 possible problems (dependent on the implementation of the minimizer):
1. The parameter space is very flat for large spaces (between the half integer values) so the other parameters may get odd values
2. The perturbation for the spin becomes much larger (e.g. 10), giving rubbish results. However, the minimizer keeps going in that direction as it believes between 0 and 4 is flat. This is more likely with an adaptive step size method. I think we do use one, @MialLewis could you confirm?

**Comment by AnthonyLim23** [comment] 2022-11-25 14:56
I think we are going to have to make spin an attribute and the user will have try the different values. Unless we can find a way to override the fit method to do something different or make it an algorithm, I cannot see another way. The problem is that the spin has specific values and to then evaluate if value a is better than b we need to calculate the chi squared, which the fit function cannot do (it has no idea what the data y values are). 

The downside of making it an algorithm is that I think it will not work with the fit browser. 

@martyngigg do you have any thoughts on this?

**Comment by martyngigg** [comment] 2022-11-30 09:12
It feels like it should be an attribute to me. I think maybe an algorithm is also a little too much to wrap one fitting function. Perhaps we just document that this can be used through the fit browser but it would require manually updating the spin so it is recommended to use a script with this function to put it in a loop?

**Closed** 2022-11-30 13:21 UTC
Labels: ISIS Team: Spectroscopy, Investigation
