### ISSUE TITLE
Reflectometry GUI doesn't throw options on hard exit

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22789] opened 2018-07-05 10:36 UTC
**Original reporter:**nobody. 

### Expected behavior

When data in the table has been edited, the GUI should throw a `Save/Cancel/Discard` dialog when the `x` close button is clicked. 

The expected behaviour is described in the [unscripted testing](https://www.mantidproject.org/Testing_ISIS_Reflectometry_GUI#Reflectometry_New), under the heading "Closing the GUI".

### Actual behavior

The GUI simply closes with no options and the changes are lost.

### Steps to reproduce the behavior

* Open the SANS GUI
* Import a table file - eg `INTER_NR_test.tbl` from the ISIS-Sample data.
* Edit a few of the values in the table.
* Close the GUI with `x`, without saving anything.

### Platforms affected

OSX/Windows

**Comment by gemmaguest** [comment] 2019-07-24 18:44
Duplicate of #22051

**Closed by gemmaguest** 2019-07-24 18:44 UTC
Labels: Component: GUI, Component: Reflectometry, ISIS Team: LSS
