### ISSUE TITLE
Allow plots to show x squared as the base axis.

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#10795] opened 2014-07-17 14:00 UTC
This issue was originally [TRAC 9953](http://trac.mantidproject.org/mantid/ticket/9953)

Allow a user to plot a WS in x^2 by changing axis (like linear`<>`log).

From Spencer

**Comment by martyngigg** [comment] 2015-08-03 08:07
Duplicate of #11422

**Closed** 2015-08-03 10:43 UTC
Labels: Component: GUI, State: Review Required
