### ISSUE TITLE
Crash when removing detector IDs in MuonAnalysis

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#15514] opened 2016-03-02 09:51 UTC
To reproduce:
- Open the MuonAnalysis interface and load a dataset
- Go to "Grouping Options" and remove the detector IDs in one of the groups in the "Group Table". Hit enter or click in the next group
- Mantid crashes

**Comment by tom-perkins** [comment] 2016-09-22 10:22
Can't reproduce this bug any more - perhaps it has been fixed in the meantime.
When I remove the detector IDs in a group, it plots another group instead and does not crash.

**Closed** 2017-01-16 11:26 UTC
Labels: Component: GUI, Component: Muon, State: Review Required
