### ISSUE TITLE
Mantid crash in IPython on Windows

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#30297] opened 2021-01-08 16:18 UTC
Go to the IPython window in workbench

type `from mantid.kernel` then press tab to auto complete
CRASH!

![image](https://user-images.githubusercontent.com/25006392/104038533-2670bc00-51cd-11eb-942a-7beb379cf99b.png)

**Comment by martyngigg** [comment] 2021-01-11 08:14
This is a duplicate of #11286 and only affects Debug builds so I'm going to close this one.

**Closed** 2021-01-11 08:14 UTC
Labels: High Priority, ISIS Team: Core
