### ISSUE TITLE
Unreliable unit test - ConvertEventsToMDTest

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#14925] opened 2016-01-11 11:09 UTC
`ConvertEventsToMDTest` has been persistently failing (899!= 900) in a small percentage of runs (say 5-10%?) for some time now. Only on windows (debug and release). I'd suspect this started with the upgrade to MSVC2015.  The issue could be a false positive or a glitch in the test and not the tested code. The test generates the 900 events with `rand()`. Someone that understands well that test and how the random integers are mapped into Q space: could  a poor `rand()` be generating events outside of the normal expected cube, or duplicate/invalid events?

**Comment by martyngigg** [comment] 2016-01-11 11:10
It has been suggested that `rand()` is not threadsafe and could be the cause of the random failures.

As a modernization task  `rand()` probably should be changed to instead use <random>.

**Comment by FedeMPouzols** [comment] 2016-01-11 11:11
Sorry I missed this. There's an older duplicate of this issue: #14556.

**Comment by martyngigg** [comment] 2016-01-11 11:13
My fault, I missed it. I'll close this as a duplicate.

**Comment by FedeMPouzols** [comment] 2016-01-11 11:13
If I remember correctly, the test also fails single-threaded runs if you run it in a loop enough times. I'll check if the modernization fixes the issue.

**Closed** 2016-01-13 14:20 UTC
Labels: Component: Framework, State: Review Required
