### ISSUE TITLE
Polynomial Transmission Correction

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12523] opened 2015-05-01 15:38 UTC
This issue was originally [TRAC 11685](http://trac.mantidproject.org/mantid/ticket/11685)

The old version of quick used to create a transmission workspace based on polynomials in the parameter file. We need some way to get this into the new workflow algorithms.

1. Confirm that if I don't set a transmission workspace. It defaults to perform not transmission correction. This is important because I think that's what we should be doing if we divide by a direct beam region.
1. Figure out how and where to insert this behaviour. I would prefer this to be  in the remit of CreateTramsissionWorkspace (and auto version) with a flag in the ReflectometryReductionAlgorithm (and auto version) to switch this behaviour on/off.
1. Apply the above.

 - - - - 
Keywords: workflow

**Comment by eXeC64** [comment] 2015-06-04 13:01
This is a duplicate of #11428.

**Closed by eXeC64** 2015-06-04 13:01 UTC
Labels: High Priority, Reflectometry
