### ISSUE TITLE
EnggGUI: preIntegFile and PreCurveFIle files not saved after EnggVaandiumCorrection

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#16195] opened 2016-05-13 08:10 UTC
### Expected behavior

When new calibration is carried out, if the file is found; the `EnggVanadiumCorrection` are calculated first which produces `preIntegFile` and `preCurveFile`. These files should be saved so next time `EnggVanadiumCorrection` wont have to be calculated for the same `vanadium` and `ceria` run number and existing `preIntegFile` and `preCurveFile` can simply be loaded, which would save sufficient time and speed up the calibration process.
### Actual behavior

Currently `EnggVanadiumCorrection` are being calculated every time the calibration is carried out as the `preIntegFile`. 
### Steps to reproduce the behavior

Run calibraiton on `EngineeringDiffraction` GUI
### Platforms affected

All

**Comment by FedeMPouzols** [comment] 2016-05-13 08:19
This is more a missing feature than a bug. The interface is smart enough to reload precalculated results but not enough to save them for new vanadium runs. So let's give it lower priority than the other issues, especially for the beta testing period where we should minimize changes and avoid risks.

**Comment by NickDraper** [comment] 2016-05-20 08:55
If this is low priority should we move it to R3.8?

**Comment by FedeMPouzols** [comment] 2016-05-20 08:56
Yes, definitely.

**Comment by shahrozahmed1** [comment] 2016-06-17 10:04
- [ ] Prerequisite #16649

**Comment by DavidFair** [comment] 2016-09-12 16:11
I need to check if #17424 is a duplicate of this or this is a separate issue.

**Comment by FedeMPouzols** [comment] 2016-09-16 09:34
Yes, #17424 and this issue are the same.

**Closed** 2017-01-16 11:25 UTC
Labels: Component: Diffraction, Component: GUI, State: Review Required
