### ISSUE TITLE
changing between seqfit all and fit and back in muon analysis removes fit status

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#32984] opened 2021-11-16 11:47 UTC
Going from Seq fit all back to fit to refit a single run and then go back to Seq fit removes Fit status & Chi squared.

**Comment by AnthonyLim23** [comment] 2021-11-16 15:17
duplicate of https://github.com/mantidproject/mantid/issues/32838

**Closed by AnthonyLim23** 2021-11-16 15:17 UTC
Labels: Bug, Muon, ISIS Team: Spectroscopy
