### ISSUE TITLE
Improve ability to work in detector coordinates

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12065] opened 2015-03-04 11:37 UTC
This issue was originally [TRAC 11226](http://trac.mantidproject.org/mantid/ticket/11226)

Mantid does not currently offer many mechanisms to work with detector coordinates.

Both Pascal Manuel & Leighton Coates expressed interest in this area although it is not yet clear what their requirements are.

Gather requirements & allow a 2 week timebox for implementation

 - - - - 
Keywords: SSC 2015 all SX

**Comment by NickDraper** [comment] 2016-06-14 11:08
Duplicate of #15546

**Closed by NickDraper** 2016-06-14 11:08 UTC
Labels: Component: Diffraction, Group: Single Crystal, Misc: SSC, Priority: High, State: Review Required
