### ISSUE TITLE
Testing the exercises in the mantid basics tutorial for the training 

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#28149] opened 2020-02-28 14:26 UTC
The training course has exercises for each of the sections below that need to be tested on workbench.

- [x] Loading and Displaying Data
- [x] Algorithms, Workspaces and Histories
- [x] Connecting Data To Instruments
- [x] Fitting Data
- [x] Mantid Plot

Build a docs-html target of Mantid and then comment on this issue which section you are testing so that other people will know. Tick the checkbox when you've finished testing and there were no issues.

**Comment by RichardWaiteSTFC** [comment] 2020-02-28 14:28
I will test:
Loading and displaying data
Mantid Plot

**Comment by RichardWaiteSTFC** [comment] 2020-02-28 15:38
In Algorithms, Workspaces and histories Ex1 - the last instruction should be point 7, and it's not clear what is required (just to show the history?)

**Comment by PhilColebrooke** [comment] 2020-03-03 14:29
I've found what looks like a formatting error on the Workbench Main Window Page
https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/getting_started/main_window.html
![image](https://user-images.githubusercontent.com/52415735/75785231-4fc5ed80-5d5b-11ea-9738-e22d16a63d66.png)

**Comment by DavidFair** [comment] 2020-03-04 14:01
I'll take algs, ws and histories

**Comment by PhilColebrooke** [comment] 2020-03-04 14:11
Do your APR David

**Comment by DavidFair** [comment] 2020-03-04 14:29
Some minor nit picks:
In "What is a Bin?...", 
- Typo `deteremines` and the comma afterwards is incorrect
- The colour fill plot has a completely different scale (which looks wrong), it looks the same in 4.2, so I don't think it's a regression for this release?
- `except for data collected in monitors, are as Event data.` -> `except for data collected in monitors, is in Event mode.`
- `Observe that as the bins get larger`, we should state something like `Observe in a plot for each that as the bins get larger`

In Algorithm histories:
- `paste what was copied to the clipboard.` You need to add, `without deleting the template code` since I instinctively did a CTRL+A / Del 

Interfaces:
- `and browse to the “loqdemo” folder` this is in ISIS Sample Data not the Training course data, it might be worth adding words to that effect

> Do your APR David

Already done :)

**Comment by DanielMurphy22** [comment] 2020-03-05 10:52
@DavidFair the Loqdemo folder is now in TrainingCourseData if you redownload it! Did the ISIS SANS interface example work for you?

**Comment by DavidFair** [comment] 2020-03-05 11:07
Yes, but I used my copy from the SampleData folder I had locally, rather than redownload hence I didn't notice the issue

**Comment by DanielMurphy22** [comment] 2020-03-05 11:08
Cool I'll fix

**Comment by Harrietbrown** [comment] 2020-03-09 10:35
Fixed by #28246

**Closed by Harrietbrown** 2020-03-09 10:35 UTC
Labels: Manual Tests
