### ISSUE TITLE
Reflectometry GUI scale of 0 causes crash

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#24252] opened 2018-12-05 13:54 UTC
### Expected behavior
* The reflectometry gui should not allow you to scale to 0 as it makes the result unplotable. This could be stopped by validation for non zero?

### Actual behavior
* If you process data with the scale set to 0 and then attempt to plot the data mantid crashes

### Steps to reproduce the behavior
* Open GUI
* Select instrument INTER in the table enter a row with run number 13460 and angle 0.5.
* Set Scale to 0 
* Process 
* Right click the data and plot
* Observe crash in mantid

### Platforms affected
* Windows 10

**Comment by gemmaguest** [comment] 2018-12-07 10:41
The exception is caused by a separate issue #23114.

It would be good to mandate the scale is not zero on the GUI and also in `ReflectometryReductionOneAuto`. Plotting `IvsQ_binned_13460` in this example gives the same error:
```
LoadNexus(Filename='INTER13460', OutputWorkspace='TOF_13460')
ReflectometryReductionOneAuto(InputWorkspace='TOF_13460', ThetaIn=0.7, ScaleFactor=0, OutputWorkspaceBinned='IvsQ_binned_13460', OutputWorkspace='IvsQ_13460', OutputWorkspaceWavelength='IvsLam_13460')
```

The GUI change should be addressed in the restructuring (#23630). I don't think this is high priority because the problem has existed for some time and never been noticed by users.

**Closed** 2019-09-16 09:00 UTC
Labels: Bug, ISIS Team: LSS, MantidPlot, Reflectometry
