### ISSUE TITLE
SANS v2 - Error when changing a table cell in the Run tab

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24243] opened 2018-12-05 10:24 UTC
### Actual behavior
The following error appears:
![image](https://user-images.githubusercontent.com/40830825/49507214-e6b1aa80-f877-11e8-9c7c-709ed15eb8f0.png)

### Steps to reproduce the behavior
1. Open Interfaces > SANS > SANS v2
2. Choose Load User File; from the ISIS sample data in the loqdemo
folder, choose Maskfile.txt
3. Choose Load Batch File; from the ISIS sample data in the
loqdemo folder, choose
batch_mode_reduction.csv
4. Click Process and wait
5. Change the first column of the first row to 74045
An error appears

### Platforms affected
All

**Comment by TTitcombe** [comment] 2018-12-05 10:33
@Mantid-Matthew this is expected behaviour, isn't it?

**Comment by Mantid-Matthew** [comment] 2018-12-05 10:57
I don't think so and even if it is it shouldn't be throwing an unexpected exception. The error seems to be coming from the FilterModel which is the same place which is causing some of the hard crashes on data entry we are seeing.

**Comment by TTitcombe** [comment] 2018-12-07 13:21
Duplicate of #23974 
Both raise the same error from similar actions: putting unexpected data in the table and **pressing enter** (rather than clicking away)

**Comment by TTitcombe** [comment] 2018-12-07 13:22
Duplicate of #23974 
Both raise the same error from similar actions: putting unexpected data in the table and **pressing enter** (rather than clicking away)

**Closed by TTitcombe** 2018-12-07 13:22 UTC
Labels: Component: SANS, Misc: Bug
