### ISSUE TITLE
ISIS Reflectometry: Save ASCII is working on using deprecated algorithm

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#26395] opened 2019-07-18 14:20 UTC
### Expected behavior
Don't use the deprecated algorithm

### Actual behavior
Uses it

### Steps to reproduce the behavior
Open Workbench->ISIS Reflectometry
Process INTER run number 13460, angle 0.5
![image](https://user-images.githubusercontent.com/24723609/61465128-5e4bca00-a96f-11e9-9fcc-9bc4eda140e5.png)
Switch to SaveASCII tab, select a workspace and some logged parameters and save
See the errors:
```
SaveReflCustomAscii is deprecated (on 2018-06-29). Use SaveReflectometryAscii instead.
SaveReflCustomAscii started
SaveReflCustomAscii successful, Duration 0.01 seconds
SaveILLCosmosAscii is deprecated (on 2018-06-29). Use SaveReflectometryAscii instead.
SaveILLCosmosAscii started
SaveILLCosmosAscii successful, Duration 0.00 seconds
SaveANSTOAscii is deprecated (on 2018-06-29). Use SaveReflectometryAscii instead.
SaveANSTOAscii started
SaveANSTOAscii successful, Duration 0.01 seconds
```

### Platforms affected
All

**Comment by gemmaguest** [comment] 2019-07-23 13:21
Closing as this is a duplicate of #24429

**Closed by gemmaguest** 2019-07-23 13:21 UTC
Labels: Component: GUI, Component: Reflectometry
