### ISSUE TITLE
Replacing 3D workspace when open in sliceviewer causes unhandled exception when panning/zooming

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33884] opened 2022-05-12 08:45 UTC
(1) Run this script
```
md_4D = CreateMDWorkspace(Dimensions=4, Extents=[-2,2,-1,1,-1.5,1.5,-0.25,0.25], Names="H,K,L,E", Frames='HKL,HKL,HKL,General Frame',Units='r.l.u.,r.l.u.,r.l.u.,meV')
FakeMDEventData(InputWorkspace=md_4D, UniformParams='5e5') # 4D data
tmp = CreateMDWorkspace(Dimensions=4, Extents=[-0.5,0.5,-1,-0.5,-1.5,-1, -0.25,0], Names="H,K,L,E", Frames='HKL,HKL,HKL,General Frame',Units='r.l.u.,r.l.u.,r.l.u.,meV')
FakeMDEventData(InputWorkspace=tmp, UniformParams='1e5') # 4D data
md_4D += tmp
DeleteWorkspace(tmp)

# Add a non-orthogonal UB
expt_info = CreateSampleWorkspace()
md_4D.addExperimentInfo(expt_info)
SetUB(Workspace='md_4D', c=2, gamma=120)

# make a 3D MDEvent workspace by integrating over all E
md_3D = SliceMD(InputWorkspace='md_4D', AlignedDim0='H,-2,2,100', AlignedDim1='K,-1,1,100', AlignedDim2='L,-1.5,1.5,100')
```
(2) Open `md_3d` in sliceviewer
(3) Run script in (1) again

Exception:
```
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\mantid\simpleapi.py", line 920, in do_set_property
    if isinstance(new_value, _kernel.DataItem) and new_value.name():
RuntimeError: Variable invalidated, data has been deleted.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\presenters\zoom.py", line 72, in zoom_fun
    callback()
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\views\dataview.py", line 421, in on_data_limits_changed
    self.presenter.data_limits_changed()
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\presenters\base_presenter.py", line 54, in data_limits_changed
    self.new_plot()  # automatically uses current display limits
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\presenters\presenter.py", line 95, in new_plot
    self._new_plot_method(*args, **kwargs)
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\presenters\presenter.py", line 130, in new_plot_MDE
    self.model.get_ws_MDE(slicepoint=self.get_slicepoint(),
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\models\model.py", line 175, in get_ws_MDE
    binned = BinMD(InputWorkspace=workspace, OutputWorkspace=self._rebinned_name, **params)
  File "C:\MantidNightlyInstall\bin\mantid\simpleapi.py", line 1056, in __call__
    set_properties(algm, *args, **final_keywords)
  File "C:\MantidNightlyInstall\bin\mantid\simpleapi.py", line 944, in set_properties
    do_set_property(key, value)
  File "C:\MantidNightlyInstall\bin\mantid\simpleapi.py", line 927, in do_set_property
    raise e.__class__(msg) from e
RuntimeError: Problem setting "InputWorkspace" in BinMD-v1: Variable invalidated, data has been deleted.
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\presenters\zoom.py", line 72, in zoom_fun
    callback()
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\views\dataview.py", line 421, in on_data_limits_changed
    self.presenter.data_limits_changed()
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\presenters\base_presenter.py", line 53, in data_limits_changed
    if WorkspaceInfo.can_support_dynamic_rebinning(self.model.ws):
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\models\workspaceinfo.py", line 38, in can_support_dynamic_rebinning
    ws_type = WorkspaceInfo.get_ws_type(workspace)
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\models\workspaceinfo.py", line 26, in get_ws_type
    if workspace.isMDHistoWorkspace():
RuntimeError: Variable invalidated, data has been deleted.
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\presenters\zoom.py", line 72, in zoom_fun
    callback()
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\views\dataview.py", line 421, in on_data_limits_changed
    self.presenter.data_limits_changed()
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\presenters\base_presenter.py", line 53, in data_limits_changed
    if WorkspaceInfo.can_support_dynamic_rebinning(self.model.ws):
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\models\workspaceinfo.py", line 38, in can_support_dynamic_rebinning
    ws_type = WorkspaceInfo.get_ws_type(workspace)
  File "C:\MantidNightlyInstall\bin\mantidqt\widgets\sliceviewer\models\workspaceinfo.py", line 26, in get_ws_type
    if workspace.isMDHistoWorkspace():
RuntimeError: Variable invalidated, data has been deleted.
```

**Comment by ConorMFinn** [comment] 2022-05-27 08:46
I no longer seem to be able to reproduce this, on Ubuntu and macOS at any rate. @RichardWaiteSTFC Would you be able to check this on a windows conda &/or non-conda build?

**Comment by RichardWaiteSTFC** [comment] 2022-05-27 09:05
I can't reproduce this either on windows nightly conda from 9th May (I think it was conda from the manual testing?). I will try on IDAaaS

**Comment by ConorMFinn** [comment] 2022-05-27 09:15
I'll try it on a conda macOS package, and then if it works there I'll call it closed

**Comment by ConorMFinn** [comment] 2022-05-27 09:32
I can't reproduce this on any of the platforms we originally found it on. Seems to have been fixed by changes made in other PRs

**Closed by ConorMFinn** 2022-05-27 09:32 UTC
Labels: ISIS Team: Core
