### ISSUE TITLE
Workspace Calculator Doing Operations With the Same Workspace on Both Sides Will Scale Both

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/mantid#36827] opened 2024-02-07 15:58 UTC
**Describe the bug**
When both sides of the calculation use the same workspace, then the scale applied to the RHS will override the LHS and be used for both. 

**To Reproduce**
1. Load/Create a workspace
2. Set the LHS scale to 1 and the RHS scale to 2.
3. Set the sign to be `+`
4. Use the loaded workspace on both sides. 
5. Click Go. 
6. Plot your output workspace over the original one. 
7. See that the output is 4x as big as the original.

**Expected behavior**
It should be 3x. It seems to be scaling both sides. 

**Additional context**

**Comment by thomashampson** [comment] 2024-02-08 16:22
duplicate of https://github.com/mantidproject/mantid/issues/36736

**Closed** 2024-02-09 09:23 UTC
Labels: Bug, GUI, ISIS Team: LSS
