### ISSUE TITLE
Prevent script window crash

### ISSUE THREAD

**Issue by vreimund** [mantidproject/mantid#22028] opened 2018-03-09 13:00 UTC
The following script crashes Mantid when run in the script window (tested on Ubuntu 16.04):

```Python
A = CreateSampleWorkspace()
a_title = A.getRun().getProperty('run_title')
A = CreateSampleWorkspace()
A.setTitle(a_title.value)
```

First investigations and ideas in: https://github.com/mantidproject/mantid/pull/22011

**Comment by martyngigg** [comment] 2020-10-06 07:34
Closing as a duplicate of #27929

**Closed by martyngigg** 2020-10-06 07:34 UTC
Labels: Bug
