### ISSUE TITLE
Bring OSX packaging in line with other platforms

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27524] opened 2019-11-29 11:12 UTC
Currently OSX does not package separate builds for unstable and nightly installs, additionally we have not added a space between Mantid and Plot

We should tackle both at the same time on the platform

**Comment by DanielMurphy22** [comment] 2020-04-29 16:21
Removing MantidPlot label so this doesn't get closed after we drop MantidPlot

**Comment by martyngigg** [comment] 2020-11-20 08:22
Closing as a duplicate of #27453

**Closed by martyngigg** 2020-11-20 08:22 UTC
Labels: ISIS Team: Core, Workbench, macOS Only
