### ISSUE TITLE
Long numpy arrays get corrupted after using mantid.simpleapi.CreateWorkspace

### ISSUE THREAD

**Issue by bb511** [mantidproject/mantid#23336] opened 2018-08-24 10:01 UTC
### Expected behavior
Workspace should be created using msapi.CreateWorkspace and then input arrays should be able displayed through print or used in any other way.
### Actual behavior
For long numpy arrays (shortest tested for which the error occured was 2000 elements long 1D array) that are stored in a class, applying msapi.CreateWorkspace and then printing one of the input arrays makes the script crash (i.e. mantidpython has stopped working if running in mantidpython terminal).
### Steps to reproduce the behavior
The following script reproduces the behaviour if ran on the mantidpython terminal on my machine:
```
import mantid.simpleapi as msapi

class FittingTestProblem:
    def __init__(self):
        self.data_x = None
        self.data_y = None
        self.data_e = None

wks = msapi.Load(Filename='ENGINX193749_calibration_spec651.nxs')
problem = FittingTestProblem()
problem.data_x = wks.readX(0)
problem.data_y = wks.readY(0)
problem.data_e = wks.readE(0)

wks = msapi.CreateWorkspace(problem.data_x, problem.data_y,
                            problem.data_e)
print(problem.data_e)
```
The ENGINX193749_calibration_spec651.nxs can be downloaded from [here](https://github.com/mantidproject/fitbenchmarking/blob/master/benchmark_problems/Neutron_data/data_files/ENGINX193749_calibration_spec651.nxs).
**Notes**: If the the variable name `wks` is changed to not be the same in both msapi.Load and msapi.CreateWorkspace lines, the problem is avoided. Additionally, the crash seems to only happen when using numpy arrays stored in a class.
### Platforms affected
Windows (have not tested on other platforms).

**Comment by martyngigg** [comment] 2021-02-04 13:09
This is actually somewhat of an issue of understanding what is happening with the memory.

`workspace.readX/Y/E` return a thin numpy-wrapper around the allocated memory in the workspace. Overwriting it with a new workspace of the same name has deleted the memory and so it will appear corrupted. In this case `CreateWorkspace` takes a copy and sees the correct data but the print statement sees invalid data.

Closing as works as intended.

**Closed by martyngigg** 2021-02-04 13:09 UTC
